# AWS CloudFront CDN Configuration
# For Church Management Application
# ============================================
# This is a CloudFormation template for setting up CloudFront CDN
# Usage: aws cloudformation deploy --template-file cdn-cloudfront.yml --stack-name church-app-cdn
# ============================================

AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFront CDN for Church Management Application"

Parameters:
  DomainName:
    Type: String
    Description: "The domain name for the application (e.g., church.example.com)"

  OriginDomain:
    Type: String
    Description: "The origin server domain (e.g., origin.church.example.com)"

  CertificateArn:
    Type: String
    Description: "ACM Certificate ARN for HTTPS (must be in us-east-1)"

  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
    Description: "Deployment environment"

Resources:
  # S3 bucket for static assets
  StaticAssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${DomainName}-static-assets"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: [GET, HEAD]
            AllowedOrigins: ["*"]
            MaxAge: 3600

  # CloudFront Origin Access Identity
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "OAI for ${DomainName}"

  # S3 bucket policy for CloudFront
  StaticAssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticAssetsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontRead
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
            Action: s3:GetObject
            Resource: !Sub "${StaticAssetsBucket.Arn}/*"

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub "Church App CDN - ${Environment}"
        DefaultRootObject: index.html
        Aliases:
          - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

        # Origins
        Origins:
          # Primary origin - Application server
          - Id: AppOrigin
            DomainName: !Ref OriginDomain
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols: [TLSv1.2]
            OriginCustomHeaders:
              - HeaderName: X-Forwarded-Host
                HeaderValue: !Ref DomainName

          # Static assets from S3
          - Id: S3StaticOrigin
            DomainName: !GetAtt StaticAssetsBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"

        # Default behavior (HTML/SPA)
        DefaultCacheBehavior:
          TargetOriginId: AppOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          Compress: true
          CachePolicyId: !Ref HTMLCachePolicy
          OriginRequestPolicyId: !Ref OriginRequestPolicy

        # Cache behaviors for different content types
        CacheBehaviors:
          # Static assets with long cache
          - PathPattern: "/assets/*"
            TargetOriginId: S3StaticOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD]
            CachedMethods: [GET, HEAD]
            Compress: true
            CachePolicyId: !Ref StaticAssetsCachePolicy

          # API requests (no caching)
          - PathPattern: "/api/*"
            TargetOriginId: AppOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT]
            CachedMethods: [GET, HEAD]
            Compress: true
            CachePolicyId: !Ref APICachePolicy
            OriginRequestPolicyId: !Ref APIOriginRequestPolicy

          # WebSocket connections
          - PathPattern: "/ws/*"
            TargetOriginId: AppOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD, OPTIONS]
            CachedMethods: [GET, HEAD]
            CachePolicyId: !Ref WebSocketCachePolicy

        # Custom error responses (SPA routing)
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0

        # Logging
        Logging:
          Bucket: !GetAtt LogBucket.DomainName
          Prefix: "cloudfront/"
          IncludeCookies: false

        PriceClass: PriceClass_100 # Use only NA and EU edge locations
        HttpVersion: http2and3
        IPV6Enabled: true

  # Cache policy for HTML (short cache)
  HTMLCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub "${AWS::StackName}-html-cache"
        DefaultTTL: 300 # 5 minutes
        MaxTTL: 3600 # 1 hour
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true

  # Cache policy for static assets (long cache)
  StaticAssetsCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub "${AWS::StackName}-static-cache"
        DefaultTTL: 31536000 # 1 year
        MaxTTL: 31536000
        MinTTL: 31536000
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true

  # Cache policy for API (no cache)
  APICachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub "${AWS::StackName}-api-cache"
        DefaultTTL: 0
        MaxTTL: 0
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: all
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true

  # Cache policy for WebSocket
  WebSocketCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub "${AWS::StackName}-websocket-cache"
        DefaultTTL: 0
        MaxTTL: 0
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: whitelist
            Headers:
              - Sec-WebSocket-Key
              - Sec-WebSocket-Version
              - Sec-WebSocket-Protocol
              - Sec-WebSocket-Extensions
          QueryStringsConfig:
            QueryStringBehavior: none
          EnableAcceptEncodingGzip: false
          EnableAcceptEncodingBrotli: false

  # Origin request policy
  OriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: !Sub "${AWS::StackName}-origin-request"
        CookiesConfig:
          CookieBehavior: none
        HeadersConfig:
          HeaderBehavior: whitelist
          Headers:
            - Host
            - Accept
            - Accept-Language
        QueryStringsConfig:
          QueryStringBehavior: none

  # API origin request policy
  APIOriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: !Sub "${AWS::StackName}-api-origin-request"
        CookiesConfig:
          CookieBehavior: all
        HeadersConfig:
          HeaderBehavior: whitelist
          Headers:
            - Host
            - Accept
            - Authorization
            - Content-Type
            - X-Requested-With
        QueryStringsConfig:
          QueryStringBehavior: all

  # Logging bucket
  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${DomainName}-cdn-logs"
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  CloudFrontDistributionId:
    Description: "CloudFront Distribution ID"
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub "${AWS::StackName}-DistributionId"

  CloudFrontDomainName:
    Description: "CloudFront Domain Name"
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub "${AWS::StackName}-DomainName"

  StaticAssetsBucketName:
    Description: "S3 Bucket for static assets"
    Value: !Ref StaticAssetsBucket
    Export:
      Name: !Sub "${AWS::StackName}-AssetsBucket"
